-- [[ Configure and install plugins ]]
require("lazy").setup({
	require("plugins.alpha"),
	require("plugins.autopairs"),
	require("plugins.catppuccin"),
	require("plugins.comment"),
	require("plugins.completions"),
	require("plugins.conform"),
	require("plugins.copilot"),
	require("plugins.diffview"),
	require("plugins.flash"),
	require("plugins.fzf"),
	require("plugins.gitcrap"),
	require("plugins.grug"),
	-- require("plugins.illuminate"), -- replace by snacks
	require("plugins.lsp.init"),
	-- require("plugins.lsp_lines"),
	require("plugins.lualine"),
	require("plugins.mini"),
	-- require("plugins.neotree"), -- not used!
	require("plugins.session"),
	require("plugins.telescope.telescope"),
	require("plugins.toggleterm"),
	require("plugins.treesitter"),
	require("plugins.trouble"),
	require("plugins.ui"),
	require("plugins.undotree"),
	require("plugins.unception"),
	require("plugins.which_key"),
	require("plugins.zen"),
	require("plugins.snacks.init"),
	-- require("plugins.persistence"),
	--  require("plugins.lsp-config"),
	--  require("plugins.none-ls"),
	-- require("plugins.ufo"),
	-- require("plugins.neotest"),
	-- require("plugins.adopure"),
	--    "tpope/vim-sleuth",
}, {
	ui = {
		-- If you are using a Nerd Font: set icons to an empty table which will use the
		-- default lazy.nvim defined Nerd Font icons, otherwise define a unicode icons table
		icons = vim.g.have_nerd_font and {} or {
			cmd = "⌘",
			config = "🛠",
			event = "📅",
			ft = "📂",
			init = "⚙",
			keys = "🗝",
			plugin = "🔌",
			runtime = "💻",
			require = "🌙",
			source = "📄",
			start = "🚀",
			task = "📌",
			lazy = "💤 ",
		},
	},
})
