-- Maybe there is a problem with one. It seems that it is not used.
-- Is it used only if from the lsp? Do I need as a seperate .lua?
-- Exists as dependancie in the lsp/init.lua so it loads from there...
--
-- return {
-- 	{
-- 		url = "https://git.sr.ht/~whynothugo/lsp_lines.nvim",
-- 		event = "VeryLazy",
-- 		main = "lsp_lines",
-- 		config = true,
-- 	},
-- }
--
--
-- I put some notes here!
--  This needs some refinement. It seems I try to set diagnostics with this one in many places
--  however it the link to to this is not clean and it gets confusing if it is enabled disabled or if it works correctly or not
--  The main file that is super complicated is the "neovim/nvim-lspconfig",
